name: Django Testing

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: CodeQuality Flake8
        run: |
          pip install flake8
          flake8
      
      - name: Coverage for Missing Tests
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report -m
      
      - name: Django Tests
        run: |
          pytest